<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>15444c8f-d773-4fb3-8b58-feed07f6c812</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KernelErp.Core\KernelErp.Core.csproj" />
    <ProjectReference Include="..\KernelErp.Warehouse\KernelErp.Warehouse.csproj" />
    <ProjectReference Include="..\KernelErp.Infrastructure\KernelErp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
